const OPENSUBTITLES_UA: string =
    process.env.OPENSUBTITLES_UA || 'TemporaryUserAgent';
const OPENSUBTITLES_USERNAME: string = process.env.OPENSUBTITLES_USERNAME || '';
const OPENSUBTITLES_PASSWORD: string = process.env.OPENSUBTITLES_PASSWORD || '';

export { OPENSUBTITLES_UA, OPENSUBTITLES_USERNAME, OPENSUBTITLES_PASSWORD };
